### ISSUE TITLE
SyntaxError Invalid regular expression for index

### ISSUE THREAD

**Issue by ginoliang1130** [tcort/markdown-link-check#156]
Hi 

The latest version has invalid regular expression from index line 10.

`SyntaxError: Invalid regular expression: /(?<pattern>{{env\.(?<name>[a-zA-Z0-9\-_]+)}})/: Invalid group`

well, I reinstall the 3.8.5 and then test my project successfully.

**Comment by trolologuy** [comment]
Indeed, installing using:
- locally: `npm install --save-dev markdown-link-check@3.8.5`
- globally: `npm install -g markdown-link-check@3.8.5`

Solves the issue.

**Comment by NicolasMassart** [comment]
Can you tell me more about how you had this error because I can't reproduce either by running tests `npm test` or by running the checks on my projects. The regex seems fine. Thanks for your help.

**Comment by trolologuy** [comment]
On `Ubuntu 18.04.5 LTS x86_64`:

```
loadDep:request → get     ▐ ╢███████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
loadDep:marked → request  ▌ ╢█████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/markdown-link-check -> /usr/local/lib/node_modules/markdown-link-check/markdown-link-check
/usr/local/lib
└─┬ markdown-link-check@3.8.6
  ├── async@3.2.0
  ├─┬ chalk@4.1.0
  │ ├─┬ ansi-styles@4.3.0
  │ │ └─┬ color-convert@2.0.1
  │ │   └── color-name@1.1.4
  │ └─┬ supports-color@7.2.0
  │   └── has-flag@4.0.0
  ├── commander@6.2.1
  ├─┬ link-check@4.5.4
  │ ├─┬ is-relative-url@3.0.0
  │ │ └── is-absolute-url@3.0.3
  │ ├─┬ isemail@3.2.0
  │ │ └── punycode@2.1.1
  │ └── ms@2.1.3
  ├── lodash@4.17.21
  ├─┬ markdown-link-extractor@1.2.6
  │ └── marked@1.2.9
  ├── progress@2.0.3
  └─┬ request@2.88.2
    ├── aws-sign2@0.7.0
    ├── aws4@1.11.0
    ├── caseless@0.12.0
    ├─┬ combined-stream@1.0.8
    │ └── delayed-stream@1.0.0
    ├── extend@3.0.2
    ├── forever-agent@0.6.1
    ├─┬ form-data@2.3.3
    │ └── asynckit@0.4.0
    ├─┬ har-validator@5.1.5
    │ ├─┬ ajv@6.12.6
    │ │ ├── fast-deep-equal@3.1.3
    │ │ ├── fast-json-stable-stringify@2.1.0
    │ │ ├── json-schema-traverse@0.4.1
    │ │ └── uri-js@4.4.1
    │ └── har-schema@2.0.0
    ├─┬ http-signature@1.2.0
    │ ├── assert-plus@1.0.0
    │ ├─┬ jsprim@1.4.1
    │ │ ├── extsprintf@1.3.0
    │ │ ├── json-schema@0.2.3
    │ │ └─┬ verror@1.10.0
    │ │   └── core-util-is@1.0.2
    │ └─┬ sshpk@1.16.1
    │   ├── asn1@0.2.4
    │   ├── bcrypt-pbkdf@1.0.2
    │   ├── dashdash@1.14.1
    │   ├── ecc-jsbn@0.1.2
    │   ├── getpass@0.1.7
    │   ├── jsbn@0.1.1
    │   ├── safer-buffer@2.1.2
    │   └── tweetnacl@0.14.5
    ├── is-typedarray@1.0.0
    ├── isstream@0.1.2
    ├── json-stringify-safe@5.0.1
    ├─┬ mime-types@2.1.29
    │ └── mime-db@1.46.0
    ├── oauth-sign@0.9.0
    ├── performance-now@2.1.0
    ├── qs@6.5.2
    ├── safe-buffer@5.2.1
    ├─┬ tough-cookie@2.5.0
    │ └── psl@1.8.0
    ├── tunnel-agent@0.6.0
    └── uuid@3.4.0
```
and running it gives:

```
vagrant:playbook/ (master✗) $ markdown-link-check -v                                                                                                                                       [17:28:06]
/usr/local/lib/node_modules/markdown-link-check/index.js:10
const envVarPatternMatcher = /(?<pattern>{{env\.(?<name>[a-zA-Z0-9\-_]+)}})/;
                             ^

SyntaxError: Invalid regular expression: /(?<pattern>{{env\.(?<name>[a-zA-Z0-9\-_]+)}})/: Invalid group
    at Object.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/index.js:10:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:7:27)
    at Module._compile (module.js:652:30)
```

It seems to be installing `markdown-link-check@3.8.**6**` whereas it should probably be using `3.8.**5**`:
https://github.com/tcort/markdown-link-check/releases

**Comment by NicolasMassart** [comment]
I will get an Ubuntu box to check that then. Thanks for the clear details!

**Comment by NicolasMassart** [comment]
One additional question, what version of node/npm is installed on your machine please?

**Comment by trolologuy** [comment]
Nice, thank you! 
I can only recommend [vagrant](https://www.vagrantup.com/) for that.
```
vagrant:~/ (master✗) $ node -v                                                                                                                                                      
v8.10.0
vagrant:~/ (master✗) $ npm -v                                                                                                                                                       
3.5.2
```

I just noticed that [node 8.0 is EOL](https://endoflife.software/programming-languages/server-side-scripting/nodejs), that may be the issue. I should update that. Will try that and come back to you.

**Comment by trolologuy** [comment]
Apologies, `-v` is not valid as parameter for `markdown-link-check` ...
So, with an updated version of node it solves the issue.
But there is a bug on how the `-v` argument is treated, versus:
```
vagrant:~/ (master✗) $ markdown-link-check --version                                                                                                                                
error: unknown option '--version'
```

**Comment by NicolasMassart** [comment]
I will check for the `-v` then. Thanks for your feedback!
