### ISSUE TITLE
`Error: Exceeded maxRedirects`

### ISSUE THREAD

**Issue by chris-dura** [tcort/markdown-link-check#159]
I have some documentation that links out to the Android Developer docs, and they apparently have some hefty redirects going on (although, it doesn't take more than a second or two, and is definitely not "stuck in a redirect loop").

https://developer.android.com/reference/android/support/design/widget/TabItem.html

I don't want to ignore these, because I want to know if they're _truly_ dead. But, the error seems to be in the guts of some dependencies.

```shell
[
  LinkCheckResult {
    link: 'https://developer.android.com/reference/android/support/design/widget/TabItem.html',
    statusCode: 0,
    err: Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://developer.android.com/reference/android/support/design/widget/TabItem
        at Redirect.onResponse (/Users/CDura/code/kite-design-system/node_modules/request/lib/redirect.js:98:27)
        at Request.onRequestResponse (/Users/CDura/code/kite-design-system/node_modules/request/request.js:986:22)
        at ClientRequest.emit (events.js:315:20)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)
        at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
        at TLSSocket.socketOnData (_http_client.js:509:22)
        at TLSSocket.emit (events.js:315:20)
        at addChunk (_stream_readable.js:309:12)
        at readableAddChunk (_stream_readable.js:284:9)
        at TLSSocket.Readable.push (_stream_readable.js:223:10),
    status: 'dead'
  }
]
```

**Comment by NicolasMassart** [comment]
It's very strange but it seems that this is due to the user_agent used in link-check. When I remove it or change it to empty, then it perfectly works. I don't Know why Google has issues with this agent, it may be linked to the authorisation process used for this android site (if you look at the redirects stack it goes through some auth). I don't know if it's standard behaviour or a something specific to this site. I'm a bit worried that the site behaves differently depending on user agent though as it's clearly not a good filter behaviour.
Anyway this is clearly an issue on the link-check dependency side and I will create the matching issue.
Thanks for raising this.

**Comment by NicolasMassart** [comment]
I only raised the ticket, @tcort fixed it by adding a customisable user-agent.
However the markdown-link-check latest release was done before this change in link-check so it's not part of the latest release. You can manually update link-check to https://github.com/tcort/link-check/releases/tag/v5.0.0 in your packages.json file I think it's going to be compatible with MLC until @tcort releases a new version.
