### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer

### ISSUE THREAD

**Issue by cdtzabra** [tcort/markdown-link-check#206]
Hello

FYI: I have this errors log many times

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:263:10)
    at BlackHole.Writable.write (_stream_writable.js:297:21)
    at PassThrough.ondata (_stream_readable.js:710:20)
    at PassThrough.emit (events.js:198:13)
    at PassThrough.Readable.read (_stream_readable.js:505:10)
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/needle/lib/needle.js:766:32)
    at PassThrough.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:555:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at BlackHole.onerror (_stream_readable.js:734:7)
    at BlackHole.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at validChunk (_stream_writable.js:266:5)
    at BlackHole.Writable.write (_stream_writable.js:297:21)
    [... lines matching original stack trace ...]
    at PassThrough.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/node_modules/needle/lib/needle.js:766:32)
```

**Comment by max-sixty** [comment]
I'm also getting this, on checking `https://crates.io/crates/prql/`

**Comment by thepoppingone** [comment]
any resolution to this?

**Comment by tcort** [comment]
I've merged the changes into link-check and updated the dependencies of this module. The latest release should fix the problem. If not, please re-open.
