### ISSUE TITLE
--quiet isn't quiet

### ISSUE THREAD

**Issue by rpdelaney** [tcort/markdown-link-check#223]
Here's the pre-commit config I'm using:

```yaml
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.3
    hooks:
      - id: markdown-link-check
        args: [--quiet]
```

Here's what I get running it on [this messy repo right here](https://github.com/trussworks/engineering-playbook):

<details>

```
- hook id: markdown-link-check
- exit code: 1

FILE: docs/README.md

  9 links checked.

FILE: docs/developing/cicd/intro.md

  16 links checked.

FILE: docs/incident-response/security-incidents.md

  0 links checked.

FILE: docs/incident-response/on-call.md

  11 links checked.

FILE: docs/developing/learning/asking_for_help.md

  0 links checked.

FILE: docs/infrasec/bootstrap.md
  [✖] https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch

  13 links checked.

  ERROR: 1 dead links found!
  [✖] https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch → Status: 403

FILE: docs/developing/pairing/meeting-attendance.md

  1 links checked.

FILE: docs/developing/learning/README.md

  12 links checked.

FILE: docs/developing/pairing/pairing-framework/planning-pairing.md

  0 links checked.

FILE: docs/web/api/rest-api-design/HTTP-Methods.md

  2 links checked.

FILE: docs/infrasec/terraform/terraform-import.md

  3 links checked.

FILE: docs/infrasec/certs.md

  6 links checked.

FILE: docs/infrasec/tutorials/fix-circleci-integrations.md

  4 links checked.

FILE: docs/web/testing/nightwatch.md

  1 links checked.

FILE: docs/developing/pairing/why-pair.md

  0 links checked.

FILE: docs/web/testing/README.md

  2 links checked.

FILE: docs/developing/nix/README.md
  [✖] #profiles:-advanced

  13 links checked.

  ERROR: 1 dead links found!
  [✖] #profiles:-advanced → Status: 404

FILE: docs/infrasec/aws/guardduty.md

  5 links checked.

FILE: docs/developing/cycle/README.md

  2 links checked.

FILE: docs/infrasec/aws/sns-guardduty-alert-integrations.md

  36 links checked.

FILE: docs/infrasec/pro-dev.md

  8 links checked.

FILE: docs/infrasec/aws/naming.md

  16 links checked.

FILE: docs/developing/pairing/etiquette.md

  0 links checked.

FILE: docs/developing/technical-design/README.md

  6 links checked.

FILE: docs/practices/appeng/adrs/0002-distributed-tracing.md

  3 links checked.

FILE: docs/developing/languages/python/project_setup.md

  3 links checked.

FILE: docs/web/api/rest-api-design/Data-Design.md

  6 links checked.

FILE: docs/developing/learning/radical_candor.md

  2 links checked.

FILE: docs/infrasec/tutorials/README.md
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/docs/how-to/setup-new-user.md

  6 links checked.

  ERROR: 1 dead links found!
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/docs/how-to/setup-new-user.md → Status: 404

FILE: docs/developing/pairing/pairing-framework/mentoring-pairing.md

  0 links checked.

FILE: docs/web/frontend/react.md
  [✖] https://react.rocks/tag/Bootstrap
  [✖] https://facebook.github.io/react/docs/jsx-gotchas.html
  [✖] https://github.com/reactjs/react-router
  [✖] http://revelry.co/react-testing-with-jasmine/react-addons-test-utils
  [✖] https://github.com/tommyh/jasmine-react
  [✖] https://github.com/airbnb/enzyme
  [✖] https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md
  [✖] https://github.com/blainekasten/jasmine-enzyme
  [✖] https://github.com/mmanela/chutzpah/wiki

  49 links checked.

  ERROR: 9 dead links found!
  [✖] https://react.rocks/tag/Bootstrap → Status: 0
  [✖] https://facebook.github.io/react/docs/jsx-gotchas.html → Status: 404
  [✖] https://github.com/reactjs/react-router → Status: 429
  [✖] http://revelry.co/react-testing-with-jasmine/react-addons-test-utils → Status: 404
  [✖] https://github.com/tommyh/jasmine-react → Status: 429
  [✖] https://github.com/airbnb/enzyme → Status: 429
  [✖] https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md → Status: 429
  [✖] https://github.com/blainekasten/jasmine-enzyme → Status: 429
  [✖] https://github.com/mmanela/chutzpah/wiki → Status: 429

FILE: docs/developing/pairing/what-doesnt-work-well.md

  0 links checked.

FILE: docs/developing/growth/README.md

  1 links checked.

FILE: docs/developing/nix/HOWTO.md

  4 links checked.

FILE: docs/practices/appeng/decision-process.md
  [✖] #review-meeting

  5 links checked.

  ERROR: 1 dead links found!
  [✖] #review-meeting → Status: 404

FILE: docs/developing/languages/BASH.md
  [✖] #Resources

  20 links checked.

  ERROR: 1 dead links found!
  [✖] #Resources → Status: 404

FILE: docs/developing/languages/python/linters_and_checkers.md

  2 links checked.

FILE: docs/incident-response/overview.md

  1 links checked.

FILE: docs/infrasec/terraform/terraform-state-mv.md

  5 links checked.

FILE: docs/templates/README.md

  2 links checked.

FILE: docs/web/frontend/developer-experience.md

  6 links checked.

FILE: docs/practices/appeng/decision-values.md

  2 links checked.

FILE: docs/developing/configuration/README.md

  2 links checked.

FILE: docs/incident-response/retro-template.md

  0 links checked.

FILE: docs/templates/topic.md
  [✖] #

  4 links checked.

  ERROR: 1 dead links found!
  [✖] # → Status: 404

FILE: docs/developing/pairing/what-works-well.md

  0 links checked.

FILE: docs/infrasec/terraform/atlantis.md
  [✖] https://github.com/trussworks/Engineering-Playbook/blob/main/infrasec/aws/aws-organizations.md
  [✖] https://github.com/trussworks/legendary-waddle

  11 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/trussworks/Engineering-Playbook/blob/main/infrasec/aws/aws-organizations.md → Status: 404
  [✖] https://github.com/trussworks/legendary-waddle → Status: 404

FILE: docs/web/server/go.md
  [✖] https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L23
  [✖] https://github.com/golang/go/wiki/TableDrivenTests

  20 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/jmoiron/sqlx/blob/master/sqlx.go#L23 → Status: 429
  [✖] https://github.com/golang/go/wiki/TableDrivenTests → Status: 429

FILE: docs/web/frontend/typescript.md

  7 links checked.

FILE: docs/developing/cicd/dependabot.md

  5 links checked.

FILE: docs/developing/cicd/README.md

  13 links checked.

FILE: docs/developing/technical-design/design-document-template.md

  0 links checked.

FILE: docs/incident-response/README.md

  6 links checked.

FILE: docs/infrasec/tutorials/yubikey-sso.md

  1 links checked.

FILE: docs/infrasec/good-infra.md
  [✖] https://guide.truss.works/distributed#tools-last

  21 links checked.

  ERROR: 1 dead links found!
  [✖] https://guide.truss.works/distributed#tools-last → Status: 404

FILE: README.md
  [✖] ./compliance/README.md
  [✖] ./developing/README.md
  [✖] ./documentation/README.md
  [✖] ./web/README.md
  [✖] ./infrasec/README.md
  [✖] ./leadership/README.md
  [✖] ./templates/README.md
  [✖] ./practices/README.md
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/main/developing/nix#extra-setup-only-fish-shell-users
  [✖] http://localhost:4000/Engineering-Playbook/
  [✖] https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits

  20 links checked.

  ERROR: 11 dead links found!
  [✖] ./compliance/README.md → Status: 400
  [✖] ./developing/README.md → Status: 400
  [✖] ./documentation/README.md → Status: 400
  [✖] ./web/README.md → Status: 400
  [✖] ./infrasec/README.md → Status: 400
  [✖] ./leadership/README.md → Status: 400
  [✖] ./templates/README.md → Status: 400
  [✖] ./practices/README.md → Status: 400
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/main/developing/nix#extra-setup-only-fish-shell-users → Status: 404
  [✖] http://localhost:4000/Engineering-Playbook/ → Status: 0
  [✖] https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits → Status: 403

FILE: docs/infrasec/terraform/terratest.md
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/docs/how-to/setup-new-user.md#setup-new-iam-user
  [✖] https://github.com/trussworks/legendary-waddle

  23 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/docs/how-to/setup-new-user.md#setup-new-iam-user → Status: 404
  [✖] https://github.com/trussworks/legendary-waddle → Status: 404

FILE: docs/developing/languages/python/installation.md
  [✖] https://pipenv.kennethreitz.org/en/latest/basics/#example-pipenv-workflow
  [✖] https://pipenv.kennethreitz.org/en/latest/basics/#environment-management-with-pipenv

  2 links checked.

  ERROR: 2 dead links found!
  [✖] https://pipenv.kennethreitz.org/en/latest/basics/#example-pipenv-workflow → Status: 0
  [✖] https://pipenv.kennethreitz.org/en/latest/basics/#environment-management-with-pipenv → Status: 0

FILE: docs/practices/appeng/adrs/0001-use-typescript.md

  15 links checked.

FILE: docs/developing/learning/crucial_conversations.md

  1 links checked.

FILE: docs/web/server/README.md

  1 links checked.

FILE: docs/web/browsersupport/README.md

  0 links checked.

FILE: docs/developing/pairing/pairing-framework/support-pairing.md
  [✖] #

  1 links checked.

  ERROR: 1 dead links found!
  [✖] # → Status: 404

FILE: docs/developing/command-line-tools/HOW2GORELEASER.md
  [✖] https://github.com/trussworks/legendary-waddle/tree/master/trussworks-prod/github-global
  [✖] https://github.com/trussworks/homebrew-tap

  10 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/trussworks/legendary-waddle/tree/master/trussworks-prod/github-global → Status: 429
  [✖] https://github.com/trussworks/homebrew-tap → Status: 429

FILE: docs/infrasec/charter.md

  7 links checked.

FILE: docs/web/frontend/testing.md

  5 links checked.

FILE: docs/practices/appeng/adrs/0004-postgresql-as-relational-store.md

  1 links checked.

FILE: docs/developing/vcs/git-repos.md
  [✖] https://github.com/trussworks/legendary-waddle/tree/master/trussworks-prod/github-global
  [✖] https://help.github.com/en/github/using-git/ignoring-files
  [✖] https://help.github.com/en/articles/configuring-protected-branches

  9 links checked.

  ERROR: 3 dead links found!
  [✖] https://github.com/trussworks/legendary-waddle/tree/master/trussworks-prod/github-global → Status: 404
  [✖] https://help.github.com/en/github/using-git/ignoring-files → Status: 403
  [✖] https://help.github.com/en/articles/configuring-protected-branches → Status: 403

FILE: docs/web/api/rest-api-design/Concurrency-Control.md

  1 links checked.

FILE: docs/developing/languages/python/README.md

  3 links checked.

FILE: docs/developing/vcs/tools.md

  8 links checked.

FILE: docs/developing/learning/release_it.md

  3 links checked.

FILE: docs/leadership/eng-lead/README.md

  7 links checked.

FILE: docs/infrasec/tutorials/yubikey-configuration.md
  [✖] https://support.yubico.com/support/solutions/articles/15000009591-how-to-confirm-your-yubico-device-is-genuine-with-u2f
  [✖] https://github.com/settings/keys

  51 links checked.

  ERROR: 2 dead links found!
  [✖] https://support.yubico.com/support/solutions/articles/15000009591-how-to-confirm-your-yubico-device-is-genuine-with-u2f → Status: 404
  [✖] https://github.com/settings/keys → Status: 429

FILE: docs/developing/code-reviews/great-code-reviews.md

  4 links checked.

FILE: docs/infrasec/ansible/ansible-primer.md
  [✖] https://github.com/ansible/ansible-lint

  4 links checked.

  ERROR: 1 dead links found!
  [✖] https://github.com/ansible/ansible-lint → Status: 429

FILE: docs/web/api/rest-api-design/URL-Design.md

  2 links checked.

FILE: docs/developing/open-source/README.md

  1 links checked.

FILE: docs/practices/appeng/team-charter.md

  1 links checked.

FILE: docs/developing/learning/goal.md

  2 links checked.

FILE: docs/developing/pairing/resources.md

  4 links checked.

FILE: docs/developing/code-reviews/pull-request-best-practices.md

  0 links checked.

FILE: docs/infrasec/book-club/README.md

  30 links checked.

FILE: docs/web/frontend/developing-ui.md

  18 links checked.

FILE: docs/infrasec/aws/govcloud/README.md

  8 links checked.

FILE: docs/infrasec/README.md
  [✖] https://github.com/trussworks/terraform-module-template
  [✖] https://github.com/trussworks/docker-template
  [✖] https://github.com/trussworks/golang-cli-template
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/docs/how-to/setup-new-user.md

  21 links checked.

  ERROR: 4 dead links found!
  [✖] https://github.com/trussworks/terraform-module-template → Status: 429
  [✖] https://github.com/trussworks/docker-template → Status: 429
  [✖] https://github.com/trussworks/golang-cli-template → Status: 429
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/docs/how-to/setup-new-user.md → Status: 429

FILE: docs/leadership/README.md

  2 links checked.

FILE: docs/developing/eid/README.md
node:internal/url:565
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:393:5)
    at URL.onParseError (node:internal/url:565:9)
    at new URL (node:internal/url:645:5)
    at linkCheck (/Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/node_modules/link-check/index.js:21:47)
    at /Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/index.js:118:9
    at /Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:246:13
    at replenish (/Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:446:21)
    at iterateeCallback (/Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:430:21)
    at /Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:327:20
    at /Users/ryan/.cache/pre-commit/repo5do7mnlm/node_env-system/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:248:17 {
  input: 'https://github.com:w0rp/ale',
  code: 'ERR_INVALID_URL'
}

Node.js v18.11.0

FILE: docs/infrasec/aws/sns-topics.md

  2 links checked.

FILE: docs/web/api/rest-api-design/Error-Response-Strategy.md
  [✖] https://www.baeldung.com/rest-api-error-handling-best-practices

  8 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.baeldung.com/rest-api-error-handling-best-practices → Status: 403

FILE: docs/compliance/README.md

  1 links checked.

FILE: docs/practices/README.md

  2 links checked.

FILE: docs/infrasec/aws/aws-organizations.md

  20 links checked.

FILE: docs/web/api/rest-api-design/Style-Guide.md
  [✖] https://github.com/transcom/mymove/blob/master/swagger/.spectral.yml

  2 links checked.

  ERROR: 1 dead links found!
  [✖] https://github.com/transcom/mymove/blob/master/swagger/.spectral.yml → Status: 404

FILE: docs/incident-response/external-resources.md

  10 links checked.

FILE: docs/incident-response/analysis.md

  4 links checked.

FILE: docs/developing/learning/the_effective_engineer.md

  3 links checked.

FILE: docs/documentation/adr.md
  [✖] https://github.com/adr/madr/blob/master/template/template.md
  [✖] https://adr.github.io/adr-log/

  6 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/adr/madr/blob/master/template/template.md → Status: 429
  [✖] https://adr.github.io/adr-log/ → Status: 404

FILE: docs/infrasec/ansible/README.md

  3 links checked.

FILE: docs/developing/languages/ruby/README.md

  1 links checked.

FILE: docs/leadership/eng-management/README.md
  [✖] https://github.com/ksindi/managers-playbook

  6 links checked.

  ERROR: 1 dead links found!
  [✖] https://github.com/ksindi/managers-playbook → Status: 429

FILE: docs/documentation/intro-to-docs.md

  1 links checked.

FILE: docs/developing/cicd/circleci-patterns.md
  [✖] https://support.circleci.com/hc/en-us/articles/360019182513-Build-Docker-image-in-one-job-and-use-in-another-job

  3 links checked.

  ERROR: 1 dead links found!
  [✖] https://support.circleci.com/hc/en-us/articles/360019182513-Build-Docker-image-in-one-job-and-use-in-another-job → Status: 403

FILE: docs/developing/open-source/intent.md

  4 links checked.

FILE: docs/developing/pairing/giving-feedback.md

  0 links checked.

FILE: docs/developing/cicd/circleci-utilities.md
  [✖] https://docs.github.com/en/rest/reference/
  [✖] https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  [✖] https://docs.github.com/en/rest/reference/pulls#get-a-pull-request

  6 links checked.

  ERROR: 3 dead links found!
  [✖] https://docs.github.com/en/rest/reference/ → Status: 403
  [✖] https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty- → Status: 403
  [✖] https://docs.github.com/en/rest/reference/pulls#get-a-pull-request → Status: 403

FILE: docs/web/frontend/project-checklist.md

  1 links checked.

FILE: docs/developing/languages/README.md
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/web/frontend

  15 links checked.

  ERROR: 1 dead links found!
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/web/frontend → Status: 404

FILE: docs/templates/subject/README.md
  [✖] #

  1 links checked.

  ERROR: 1 dead links found!
  [✖] # → Status: 404

FILE: CONTRIBUTING.md
  [✖] https://www.pivotaltracker.com/n/projects/2120515
  [✖] ./templates/README.md

  2 links checked.

  ERROR: 2 dead links found!
  [✖] https://www.pivotaltracker.com/n/projects/2120515 → Status: 404
  [✖] ./templates/README.md → Status: 400

FILE: docs/infrasec/tutorials/circle-ci-honeycomb-integrations.md
  [✖] https://www.honeycomb.io/

  6 links checked.

  ERROR: 1 dead links found!
  [✖] https://www.honeycomb.io/ → Status: 0

FILE: docs/web/frontend/README.md

  29 links checked.

FILE: docs/web/api/GraphQL-Design-Guide.md

  13 links checked.

FILE: docs/developing/healthcheck/README.md

  2 links checked.

FILE: docs/practices/appeng/README.md

  7 links checked.

FILE: docs/developing/vcs/git-workflow.md
  [✖] https://guides.github.com/introduction/flow/
  [✖] https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository
  [✖] https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

  7 links checked.

  ERROR: 3 dead links found!
  [✖] https://guides.github.com/introduction/flow/ → Status: 403
  [✖] https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository → Status: 403
  [✖] https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent → Status: 403

FILE: docs/developing/languages/GO.md
  [✖] https://github.com/trussworks/go-pointer-primer
  [✖] https://github.com/golang/go/wiki/Learn
  [✖] https://github.com/jmoiron/sqlx
  [✖] https://github.com/spf13/cobra
  [✖] https://github.com/felixge/httpsnoop
  [✖] https://github.com/felixge/httpsnoop#why-this-package-exists

  44 links checked.

  ERROR: 6 dead links found!
  [✖] https://github.com/trussworks/go-pointer-primer → Status: 429
  [✖] https://github.com/golang/go/wiki/Learn → Status: 429
  [✖] https://github.com/jmoiron/sqlx → Status: 429
  [✖] https://github.com/spf13/cobra → Status: 429
  [✖] https://github.com/felixge/httpsnoop → Status: 429
  [✖] https://github.com/felixge/httpsnoop#why-this-package-exists → Status: 429

FILE: docs/developing/cicd/circleci-orbs.md
  [✖] https://github.com/trussworks/legendary-waddle-dev/blob/master/.circleci/config.yml
  [✖] https://github.com/trussworks/orb-ecr-image-scan-findings/blob/master/orb.yml
  [✖] https://github.com/trussworks/trussworks-atlantis-ecs-image/pull/3

  24 links checked.

  ERROR: 3 dead links found!
  [✖] https://github.com/trussworks/legendary-waddle-dev/blob/master/.circleci/config.yml → Status: 429
  [✖] https://github.com/trussworks/orb-ecr-image-scan-findings/blob/master/orb.yml → Status: 429
  [✖] https://github.com/trussworks/trussworks-atlantis-ecs-image/pull/3 → Status: 429

FILE: docs/web/api/README.md

  2 links checked.

FILE: docs/developing/bugs/README.md

  0 links checked.

FILE: docs/documentation/external-resources.md

  10 links checked.

FILE: docs/developing/code-reviews/README.md

  6 links checked.

FILE: docs/web/README.md
  [✖] web/api/
  [✖] web/frontend/
  [✖] web/server/
  [✖] web/browsersupport/
  [✖] web/testing/

  5 links checked.

  ERROR: 5 dead links found!
  [✖] web/api/ → Status: 400
  [✖] web/frontend/ → Status: 400
  [✖] web/server/ → Status: 400
  [✖] web/browsersupport/ → Status: 400
  [✖] web/testing/ → Status: 400

FILE: docs/developing/cicd/delivery-pipeline.md

  4 links checked.

FILE: docs/infrasec/aws/org-bootstrap.md

  20 links checked.

FILE: docs/developing/vcs/README.md

  7 links checked.

FILE: docs/practices/appeng/adrs/template.md

  0 links checked.

FILE: docs/infrasec/teardown.md

  5 links checked.

FILE: docs/infrasec/ansible/molecule-primer.md

  8 links checked.

FILE: src/pages/markdown-page.md

  0 links checked.

FILE: docs/infrasec/aws/vpcs.md
  [✖] https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/vpc-endpoints.tf

  18 links checked.

  ERROR: 1 dead links found!
  [✖] https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/vpc-endpoints.tf → Status: 404

FILE: docs/developing/command-line-tools/README.md
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/developing/docker
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/developing/direnv
  [✖] https://github.com/BurntSushi/ripgrep
  [✖] https://github.com/mas-cli/mas
  [✖] https://github.com/gleitz/howdoi

  34 links checked.

  ERROR: 5 dead links found!
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/developing/docker → Status: 404
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/developing/direnv → Status: 404
  [✖] https://github.com/BurntSushi/ripgrep → Status: 429
  [✖] https://github.com/mas-cli/mas → Status: 429
  [✖] https://github.com/gleitz/howdoi → Status: 429

FILE: docs/infrasec/aws/govcloud/gov-acm.md

  1 links checked.

FILE: docs/infrasec/terraform/README.md
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/trussworks-prod/github-global/main.tf
  [✖] https://github.com/trussworks/terraform-layout-example

  25 links checked.

  ERROR: 2 dead links found!
  [✖] https://github.com/trussworks/legendary-waddle/blob/master/trussworks-prod/github-global/main.tf → Status: 429
  [✖] https://github.com/trussworks/terraform-layout-example → Status: 429

FILE: docs/developing/vcs/master-to-main.md
  [✖] https://github.com/lgarron/main-branch
  [✖] https://support.circleci.com/hc/en-us/articles/360040969693-VCS-Default-Branch-Isn-t-Reflected-on-CircleCI
  [✖] https://github.com/danger/danger-js/issues/1057

  17 links checked.

  ERROR: 3 dead links found!
  [✖] https://github.com/lgarron/main-branch → Status: 429
  [✖] https://support.circleci.com/hc/en-us/articles/360040969693-VCS-Default-Branch-Isn-t-Reflected-on-CircleCI → Status: 403
  [✖] https://github.com/danger/danger-js/issues/1057 → Status: 429

FILE: docs/developing/direnv/README.md
  [✖] https://github.com/direnv/direnv/wiki/golang
  [✖] https://github.com/direnv/direnv/pull/188
  [✖] https://github.com/direnv/direnv/wiki/Docker-Machine
  [✖] https://github.com/transcom/mymove/blob/master/.envrc

  6 links checked.

  ERROR: 4 dead links found!
  [✖] https://github.com/direnv/direnv/wiki/golang → Status: 429
  [✖] https://github.com/direnv/direnv/pull/188 → Status: 429
  [✖] https://github.com/direnv/direnv/wiki/Docker-Machine → Status: 429
  [✖] https://github.com/transcom/mymove/blob/master/.envrc → Status: 429

FILE: docs/web/testing/cypress.md

  5 links checked.

FILE: docs/infrasec/tutorials/one-time-passwords.md

  7 links checked.

FILE: docs/developing/cycle/tracker.md
  [✖] https://docs.google.com/document/d/1abmxQdYol6Zi3kR3U__JNJl3uPdKF9WPYWfu75AkZ50/edit#heading=h.yyb7wuihugn8

  4 links checked.

  ERROR: 1 dead links found!
  [✖] https://docs.google.com/document/d/1abmxQdYol6Zi3kR3U__JNJl3uPdKF9WPYWfu75AkZ50/edit#heading=h.yyb7wuihugn8 → Status: 410

FILE: docs/developing/docker/README.md

  22 links checked.

FILE: docs/infrasec/terraform/naming.md

  1 links checked.

FILE: docs/developing/languages/ruby/installation.md
  [✖] https://github.com/monfresh/install-ruby-on-macos
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/developing/docker#installation
  [✖] https://kgrz.io/programmers-guide-to-choosing-ruby-version-manager.html
  [✖] https://linhmtran168.github.io/blog/2014/02/27/moving-from-rbenv-to-chruby/

  10 links checked.

  ERROR: 4 dead links found!
  [✖] https://github.com/monfresh/install-ruby-on-macos → Status: 404
  [✖] https://github.com/trussworks/Engineering-Playbook/tree/master/developing/docker#installation → Status: 404
  [✖] https://kgrz.io/programmers-guide-to-choosing-ruby-version-manager.html → Status: 404
  [✖] https://linhmtran168.github.io/blog/2014/02/27/moving-from-rbenv-to-chruby/ → Status: 404

FILE: docs/web/api/rest-api-design/README.md

  9 links checked.

FILE: docs/developing/slack/README.md

  3 links checked.

FILE: docs/practices/appeng/adrs/README.md

  4 links checked.

FILE: docs/infrasec/aws/README.md

  6 links checked.

FILE: docs/infrasec/alert-providers.md

  9 links checked.

FILE: docs/developing/pairing/pairing-framework/formal-pairing.md
  [✖] #

  1 links checked.

  ERROR: 1 dead links found!
  [✖] # → Status: 404

FILE: docs/practices/appeng/adrs/0003-open-source-application-code.md
  [✖] https://sourcecode.cio.gov/OSS/

  6 links checked.

  ERROR: 1 dead links found!
  [✖] https://sourcecode.cio.gov/OSS/ → Status: 0

FILE: docs/web/frontend/npm.md

  1 links checked.

```

</details>

That's a lot more verbose than I expected after a `--quiet` flag. I'd prefer not to get a list of files that _didn't_ have problems (especially since there's four newlines per file).

**Comment by tcort** [comment]
should be fixed by pull request #230. new version coming soon.
