### ISSUE TITLE
Link check crashes for MSDN Blog URLs

### ISSUE THREAD

**Issue by nex3** [tcort/markdown-link-check#260]
Although the `markdownLinkCheck()` function completes, when one of these URLs is checked, it will keep the process alive for a long time and then eventually crash with the following error:

```
/home/nweiz/goog/sass/language/node_modules/async/dist/async.js:327
              throw new Error("Callback was already called.");
              ^

Error: Callback was already called.
    at /home/nweiz/goog/sass/language/node_modules/async/dist/async.js:327:21
    at /home/nweiz/goog/sass/language/node_modules/async/dist/async.js:248:17
    at /home/nweiz/goog/sass/language/node_modules/markdown-link-check/index.js:132:13
    at /home/nweiz/goog/sass/language/node_modules/link-check/lib/proto/http.js:117:21
    at done (/home/nweiz/goog/sass/language/node_modules/needle/lib/needle.js:463:14)
    at PassThrough.<anonymous> (/home/nweiz/goog/sass/language/node_modules/needle/lib/needle.js:717:9)                                                                               
    at PassThrough.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Here's a simple reproduction:

```js
const markdownLinkCheck = require('markdown-link-check');

markdownLinkCheck(
  '[link](https://blogs.msdn.microsoft.com/)',
  (error, results) => console.log({error, results}),
);
```

**Comment by nschonni** [comment]
I wonder if it's because they have weird redirects setup? The base URL redirects to https://learn.microsoft.com/en-ca/archive/blogs/, but has a delay

**Comment by nex3** [comment]
What is even the point of an issue tracker if you ignore the issues and add a bot to close the issues you ignore?
