### ISSUE TITLE
Crash: TypeError: Cannot read properties of undefined (reading 'some') (related to program.opts().ignore )

### ISSUE THREAD

**Issue by nvuillam** [tcort/markdown-link-check#297]
MegaLinter auto-upgrade job detected a crash with latest version v3.12.0 :(

Link to the job: https://github.com/oxsecurity/megalinter/actions/runs/8224703698/job/22488857571

Error detail

```sh
--Error detail:
(node:87) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/node-deps/node_modules/markdown-link-check/markdown-link-check:97
                    if (program.opts().ignore.some((ignorePath) => resolved.includes(ignorePath))) {
                                             ^

TypeError: Cannot read properties of undefined (reading 'some')
    at Command.<anonymous> (/node-deps/node_modules/markdown-link-check/markdown-link-check:97:46)
    at Command.listener [as _actionHandler] (/node-deps/node_modules/commander/lib/command.js:482:17)
    at /node-deps/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/node-deps/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/node-deps/node_modules/commander/lib/command.js:1283:27)
    at Command.parse (/node-deps/node_modules/commander/lib/command.js:909:10)
    at getInputs (/node-deps/node_modules/markdown-link-check/markdown-link-check:108:7)
    at main (/node-deps/node_modules/markdown-link-check/markdown-link-check:252:20)

Node.js v21.4.0
```

**Comment by dklimpel** [comment]
Seems a regressin in https://github.com/tcort/markdown-link-check/pull/278 and NodeJS v21

**Comment by MikeMcC399** [comment]
@dklimpel 

> - Seems a regresson in #278 and NodeJS v21

I'm not seeing any connection of this issue to the version of Node.js. It is reproducible for me on Node.js `18`, `20` and `21`. The previous version of `markdown-link-check` did not show the error `TypeError: Cannot read properties of undefined (reading 'some')` on any of the Node.js versions I listed.

**Comment by h4ck3rk3y** [comment]
Seeing this on our side as well; fixing 3.11.2 for while we wait for this to get resolved

**Comment by MikeMcC399** [comment]
It seems that the `markdown-link-check@3.12.0`  CLI will only work if the option `--ignore` is present.

The file `md.md` in the following is a markdown file with only a title, no links. It can be checked with `npx markdown-link-check md.md --ignore "dummy"`

```text
$ npx markdown-link-check md.md --ignore "dummy"

FILE: md.md
  No hyperlinks found!

  0 links checked.
```

With no `--ignore` option used, it fails:

```text
$ npx markdown-link-check md.md
...\node_modules\markdown-link-check\markdown-link-check:97
                    if (program.opts().ignore.some((ignorePath) => resolved.includes(ignorePath))) {
                                             ^

TypeError: Cannot read properties of undefined (reading 'some')
    at Command.<anonymous> (D:\github2\others\markdown-link-ignore\node_modules\markdown-link-check\markdown-link-check:97:46)
    at Command.listener [as _actionHandler] (D:\github2\others\markdown-link-ignore\node_modules\commander\lib\command.js:482:17)
    at D:\github2\others\markdown-link-ignore\node_modules\commander\lib\command.js:1283:65
    at Command._chainOrCall (D:\github2\others\markdown-link-ignore\node_modules\commander\lib\command.js:1177:12)
    at Command._parseCommand (D:\github2\others\markdown-link-ignore\node_modules\commander\lib\command.js:1283:27)
    at Command.parse (D:\github2\others\markdown-link-ignore\node_modules\commander\lib\command.js:909:10)
    at getInputs (D:\github2\others\markdown-link-ignore\node_modules\markdown-link-check\markdown-link-check:108:7)
    at main (D:\github2\others\markdown-link-ignore\node_modules\markdown-link-check\markdown-link-check:252:20)

Node.js v20.11.1
```

**Comment by CanadaHonk** [comment]
Oops, sorry! I'll take a look :)

**Comment by tcort** [comment]
Please try the latest release 3.12.1. Re-open if not fixed.

**Comment by MikeMcC399** [comment]
@tcort 

I checked my previous steps to reproduce and it looks good with  `markdown-link-check@3.12.1`  CLI  👍🏻
