### ISSUE TITLE
TypeError: Cannot read property 'status' of null

### ISSUE THREAD

**Issue by wangzw** [tcort/markdown-link-check#30]
markdown-link-check is a great tool and save me lots of time. Thanks for open source it.

I run into an error and following is the error message and Markdown content.

```
FILE: README.md
/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:55
            if(result.status === 'dead') {
                      ^

TypeError: Cannot read property 'status' of null
    at /usr/local/lib/node_modules/markdown-link-check/markdown-link-check:55:23
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/markdown-link-check/markdown-link-check:54:17
    at /usr/local/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:1126:9
    at /usr/local/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/local/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:976:17)
    at /usr/local/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:958:16
    at /usr/local/lib/node_modules/markdown-link-check/node_modules/async/dist/async.js:1123:13
    at /usr/local/lib/node_modules/markdown-link-check/index.js:32:13
    at linkCheck (/usr/local/lib/node_modules/markdown-link-check/node_modules/link-check/index.js:24:9)
```

```
wangzw:docs wangzw$ cat README.md
# 文档目录


- [**入门指南 HTML**](010-getting-started-guide/README.md)  [**PDF**](ref://010-getting-started-guide/010-getting-started-guide.pdf)

	这个指南的目的是指导你创建一个 HashData 数据仓库样例集群。你可以通过这个样例集群来测试 HashData 数据仓库的功能。

- [**管理指南 HTML**](020-admin-guide/README.md)  [**PDF**](ref://020-admin-guide/020-admin-guide.pdf)

	这部分主要介绍了 HashData 数据仓库的管理，性能监控，扩容缩容，以及系统问题排查。

- [**最佳实践 HTML**](030-best-practices/README.md)  [**PDF**](ref://030-best-practices/030-best-practices.pdf)

	此部分主要概述了 HashData 数据仓库实践中最重要的因素。

- [**开发指南 HTML**](040-developer-guide/README.md)  [**PDF**](ref://040-developer-guide/040-developer-guide.pdf)

	此部分可以帮助你了解和学习 HashData 数据仓库的内部架构，以及 HashData 数据仓库的使用。
```

I guess "ref://010-getting-started-guide/010-getting-started-guide.pdf"  trigger the error, it is ok to me to ignore such link with/without notice, but should not throw an error.

**Comment by dklimpel** [comment]
This issue seems to be very old and outdatet. The line of code `if(result.status === 'dead')` does not exists anymore.
