### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by 4lexBaum** [tcort/markdown-link-check#4]
Do your module work with node 0.12.7?

This error comes only if to many links will be checked (~ more than 150). With node 4.x are there no problems.

output:

      throw er; // Unhandled stream error in pipe.
            ^
      Error: not implemented
    at Writable._write (_stream_writable.js:430:6)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Writable.write (_stream_writable.js:217:11)
    at Request.ondata (stream.js:51:26)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\<user>\Documents\GitHub\Tutorial-C
     ontribution\node_modules\markdown-link-check\node_modules\request\request.js:985
     :12)
    at IncomingMessage.emit (events.js:107:17)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)

**Comment by tcort** [comment]
Thanks for the report. Fixed in version `1.0.2`
