### ISSUE TITLE
Docker instructions not working

### ISSUE THREAD

**Issue by 4x0v7** [tcort/markdown-link-check#44]
When using the instructions to create and run using Docker, I get the following error:

```
$ docker run --rm -i markdown-link-check < README.md
[stdin]:1
# markdown-link-check
^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at evalScript (internal/bootstrap/node.js:483:27)
    at Socket.<anonymous> (internal/bootstrap/node.js:247:15)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

If I add an ENTRYPOINT to the bottom of the Dockerfile like so:
`ENTRYPOINT [ "/src/markdown-link-check" ]`
Then It works as I expect and the output is:
```
$ docker run --rm -i markdown-link-check < README.md
[✓] https://www.npmjs.com/package/isemail
[✓] https://github.com/tcort/markdown-link-check/blob/master/LICENSE.md
```

I'll add a PR to this issue :+1:

**Comment by tcort** [comment]
Thanks for the patch! Published in v3.5.3
