### ISSUE TITLE
Providing invalid URLs as arguments causes unexpected behavior(s)

### ISSUE THREAD

**Issue by timmkrause** [tcort/markdown-link-check#51]
Regarding #40 I am currently performing some regression tests and I came across the following (just FYI, I'm already taking care of it):

URL with 404:
```
$ markdown-link-check https://github.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md

FILE: https://github.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md
No hyperlinks found!

```

URL with invalid domain:
```
$ markdown-link-check https://gitaaaaaaaaaaaaaaaahub.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND gitaaaaaaaaaaaaaaaahub.com gitaaaaaaaaaaaaaaaahub.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

Solution for URL with 404:
```
$ node markdown-link-check https://github.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md

ERROR: Received unsuccessful status code of 404!
```

Solution for URL with invalid domain:
```
$ node markdown-link-check https://gitaaaaaaaaaaaaaaaahub.com/tcort/markdown-link-check/blob/master/READMEeeeeeeee.md

ERROR: Something went wrong!
Error: getaddrinfo ENOTFOUND gitaaaaaaaaaaaaaaaahub.com gitaaaaaaaaaaaaaaaahub.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by gaurav-nelson** [comment]
This issue is also true for invalid filenames:
```
$ markdown-link-check READMEe.md -p
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'READMEe.md'

```

**Comment by gaurav-nelson** [comment]
and directories:
```
$ node markdown-link-check test/
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
```
