### ISSUE TITLE
TypeError: Cannot read property 'R_OK' of undefined

### ISSUE THREAD

**Issue by ondrej-fabry** [tcort/markdown-link-check#52]
I'm running into this error when using simple config file:

```
/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:60
        fs.access(program.config, fs.constants.R_OK, function (err) {
                                              ^

TypeError: Cannot read property 'R_OK' of undefined
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/markdown-link-check/markdown-link-check:60:47)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Config:

```json
{
    "ignorePatterns": [
        {
            "pattern": "^http"
        }
    ]
}
```

I'm running latest version: **3.6.2** with node **4.6.2** on **Ubuntu 16.04**

EDIT:

I think I found the reason why.. it seems that `fs.constants` was deprecated: https://github.com/nodejs/node/issues/8044 and people use following code for compatibility: `(fs.constants || fs).X_OK`

**Comment by ondrej-fabry** [comment]
@tcort Any blocker on this?
