### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by pdehaan** [tcort/markdown-link-check#64]
```sh
$ cat package.json | grep "markdown-link-check"
    "markdown-link-check": "3.7.2",
```

---

It seems like local files are being checked via the CLI, but I'm getting an error when using the API, and I'm not sure if it's a setting I should be using, or an issue.

```sh
$ time find . -name \*.md -not -path "**/node_modules/*" -exec $(npm bin)/markdown-link-check -c .linkcheckrc --quiet {} \;
```

☝️ That seems to work perfectly and report errors if a `[file](docs/README.md)` link is found.

---

But when I try using the API, it seems to fail on links like `[Quickstart](docs/development/quickstart.md)` with the following error:

> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string.

```js
const {readFileSync} = require("fs");
const {join} = require("path");

const markdownLinkCheck = require('markdown-link-check');

/*
const {execSync} = require("child_process");
const files = execSync("git ls-files '*.md'")
  .toString()
  .trim()
  .split("\n")
  .sort();
*/

const README = readFileSync(join(__dirname, "README.md"), "utf-8");
markdownLinkCheck(README, (err, res) => console.log(err, res));
```

```sh
$ node scrapy

Checking 'https://img.shields.io/circleci/project/mozilla/testpilot.svg'
Checking 'https://circleci.com/gh/mozilla/testpilot/'
Checking 'https://codecov.io/gh/mozilla/testpilot/branch/master/graph/badge.svg'
Checking 'https://codecov.io/gh/mozilla/testpilot'
Checking 'docs/development/quickstart.md'
url.js:150
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:150:11)
    at Object.urlParse [as parse] (url.js:144:13)
    at linkCheck (/Users/pdehaan/dev/github/mozilla/testpilot/node_modules/link-check/index.js:22:68)
    at /Users/pdehaan/dev/github/mozilla/testpilot/node_modules/markdown-link-check/index.js:64:9
    at /Users/pdehaan/dev/github/mozilla/testpilot/node_modules/async/dist/async.js:1135:9
    at replenish (/Users/pdehaan/dev/github/mozilla/testpilot/node_modules/async/dist/async.js:1011:17)
    at iterateeCallback (/Users/pdehaan/dev/github/mozilla/testpilot/node_modules/async/dist/async.js:995:17)
    at /Users/pdehaan/dev/github/mozilla/testpilot/node_modules/async/dist/async.js:969:16
    at /Users/pdehaan/dev/github/mozilla/testpilot/node_modules/async/dist/async.js:1137:13
    at /Users/pdehaan/dev/github/mozilla/testpilot/node_modules/markdown-link-check/index.js:74:13
```

**Comment by NicolasMassart** [comment]
Do you still have this issue with 3.8.3 ?
