### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

### ISSUE THREAD

**Issue by drandreaskrueger** [tcort/markdown-link-check#67]
docker build worked fine
```
docker build --tag markdown-link-check .

Sending build context to Docker daemon  326.1kB
Step 1/8 : FROM node:latest
latest: Pulling from library/node
...
Successfully built ff70a4f3fb47
Successfully tagged markdown-link-check:latest
```

but then

```
docker run --rm -i markdown-link-check < README.md

internal/fs/utils.js:454
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.stat (fs.js:843:3)
    at Command.<anonymous> (/src/markdown-link-check:57:12)
    at Command.listener (/src/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (/src/node_modules/commander/index.js:668:12)
    at Command.parse (/src/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/src/markdown-link-check:67:4)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

```

README.md was [this one](https://github.com/drandreaskrueger/chainhammer/blob/f57e53ddd6103a99e8580f637a85413f498458df/README.md)

**Comment by karfau** [comment]
Same happens when running the following nice example from the README:

`cat *.md | markdown-link-check`

Are those ways no longer supported?
