### ISSUE TITLE
"SyntaxError: Use of const in strict mode" from isemail

### ISSUE THREAD

**Issue by hugovk** [tcort/markdown-link-check#8]
isemail causes markdown-link-check 2.0.0 to fail when using it on Travis CI:

```
$ markdown-link-check /tmp/all-the-markdown.md

/home/travis/.nvm/v0.10.36/lib/node_modules/markdown-link-check/node_modules/link-check/node_modules/isemail/lib/index.js:5
const Dns = require('dns');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/markdown-link-check/node_modules/link-check/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
The command "markdown-link-check /tmp/all-the-markdown.md" exited with 8.
```

https://travis-ci.org/hugovk/botwiki.org/builds/166221070#L790

**Comment by tcort** [comment]
isemail requires a more recent version of node.js than v0.10.36.

Side note: the node.js v0.10 series is in maintenance mode and will be EOL'd in 3 weeks... https://github.com/nodejs/LTS#lts_schedule
